version: "3.8"
services:
  db:
    image: postgres:18
    container_name: ditodoondb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - C:\Docker\pgdata:/var/lib/postgresql
